version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/auth-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "org.springdoc:springdoc-openapi-starter-webmvc-api"
        update-types:
          - "version-update:semver-major"
    groups:
      auth-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/api-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "org.springdoc:springdoc-openapi-starter-webmvc-api"
        update-types:
          - "version-update:semver-major"
    groups:
      api-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/audit-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "org.springdoc:springdoc-openapi-starter-webmvc-api"
        update-types:
          - "version-update:semver-major"
    groups:
      audit-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/mailer-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "org.springdoc:springdoc-openapi-starter-webmvc-api"
        update-types:
          - "version-update:semver-major"
    groups:
      mailer-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "pip"
    directory: "/backend/notification-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      notification-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@angular-devkit/build-angular"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@angular/cli"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@angular/compiler-cli"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "jest-environment-jsdom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "jest-preset-angular"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "jsdom"
        update-types:
          - "version-update:semver-major"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"
