version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/auth-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      auth-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/api-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      api-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/audit-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      audit-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "maven"
    directory: "/backend/mailer-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      mailer-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "pip"
    directory: "/backend/notification-service"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      notification-service-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"

  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "Update"
