name: ECR Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  publish:
    uses: ./.github/workflows/_publish-images.yml
    with:
      registry_provider: ecr
      cloud_provider_region: ${{ vars.CLOUD_PROVIDER_REGION }}
      cloud_provider_role_to_assume: ${{ vars.CLOUD_PROVIDER_ROLE_TO_ASSUME }}
      image_namespace: ${{ vars.ECR_IMAGE_NAMESPACE != '' && vars.ECR_IMAGE_NAMESPACE || 'microservices' }}
      image_tag: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      push_latest: ${{ github.ref_type == 'tag' }}
